/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paquete.GUI;

import paquete.clases.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import paquete.gestion.*;

/**
 *
 * @author Nikolas
 */
public class Ventana_V2 extends javax.swing.JFrame {
    
    DefaultTableModel modelo_alumno;
    DefaultTableModel modelo_docente;
    DefaultTableModel modelo_staff;
    
    Gestion_Alumno galumnos; //gprofes, gstaff;
    Loading load = new Loading();
    
    /**
     * Creates new form Ventana_V2
     */
    public Ventana_V2() {
        
        modelo_alumno = new DefaultTableModel();
        modelo_docente = new DefaultTableModel();
        modelo_staff = new DefaultTableModel();
        
        galumnos = new Gestion_Alumno();
        //gprofes = new Gestion_Docente();
        //gstaff = new Gestion_Staff();
        
        load.LoadingScreen("Iniciando Aplicación", 40);
        
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        //SetIcon();
        
        //Tabla Alumnos
        
        
        
        modelo_alumno.addColumn("Nombre");
        modelo_alumno.addColumn("Codigo");
        modelo_alumno.addColumn("Distrito");
        modelo_alumno.addColumn("# Cursos");
        modelo_alumno.addColumn("Promedio");
        
        
        this.jTable1.setModel(modelo_alumno);
        
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        Side_Menu = new javax.swing.JPanel();
        Alum_Main_Label = new javax.swing.JLabel();
        Doc_Main_Label = new javax.swing.JLabel();
        Staff_Main_Label = new javax.swing.JLabel();
        About_Main = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CardLayout = new javax.swing.JPanel();
        About_Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Alumno_Panel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        nombre_alumno = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        distrito_alumno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TRABAJO_FINAL");
        setResizable(false);

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setDividerSize(0);

        Side_Menu.setBackground(new java.awt.Color(242, 167, 27));
        Side_Menu.setMinimumSize(new java.awt.Dimension(200, 0));
        Side_Menu.setPreferredSize(new java.awt.Dimension(250, 677));

        Alum_Main_Label.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        Alum_Main_Label.setForeground(new java.awt.Color(255, 255, 255));
        Alum_Main_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paquete/recursos/Student.png"))); // NOI18N
        Alum_Main_Label.setText("  Alumnos");
        Alum_Main_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Alum_Main_Label.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Alum_Main_LabelFocusGained(evt);
            }
        });
        Alum_Main_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Alum_Main_LabelMouseClicked(evt);
            }
        });

        Doc_Main_Label.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        Doc_Main_Label.setForeground(new java.awt.Color(255, 255, 255));
        Doc_Main_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paquete/recursos/Teacher.png"))); // NOI18N
        Doc_Main_Label.setText("  Docentes");
        Doc_Main_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Staff_Main_Label.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        Staff_Main_Label.setForeground(new java.awt.Color(255, 255, 255));
        Staff_Main_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paquete/recursos/Staff.png"))); // NOI18N
        Staff_Main_Label.setText("  Staff");
        Staff_Main_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        About_Main.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        About_Main.setForeground(new java.awt.Color(255, 255, 255));
        About_Main.setText("About");
        About_Main.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        About_Main.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                About_MainMouseClicked(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paquete/recursos/Logo.png"))); // NOI18N
        jLabel10.setAlignmentX(0.5F);

        javax.swing.GroupLayout Side_MenuLayout = new javax.swing.GroupLayout(Side_Menu);
        Side_Menu.setLayout(Side_MenuLayout);
        Side_MenuLayout.setHorizontalGroup(
            Side_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Side_MenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Side_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Side_MenuLayout.createSequentialGroup()
                        .addGroup(Side_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Staff_Main_Label)
                            .addComponent(Doc_Main_Label)
                            .addGroup(Side_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10)
                                .addComponent(Alum_Main_Label)))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Side_MenuLayout.createSequentialGroup()
                        .addComponent(About_Main)
                        .addContainerGap())))
        );
        Side_MenuLayout.setVerticalGroup(
            Side_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Side_MenuLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel10)
                .addGap(54, 54, 54)
                .addComponent(Alum_Main_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(Doc_Main_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(Staff_Main_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(317, 317, 317)
                .addComponent(About_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(Side_Menu);

        CardLayout.setLayout(new java.awt.CardLayout());

        About_Panel.setBackground(new java.awt.Color(52, 60, 64));
        About_Panel.setPreferredSize(new java.awt.Dimension(680, 600));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seleccionar las cuentas que desee gestionar.");

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Book", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Applicación Gestión de Personas");

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Book", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html>Bienvenidos al gestor de personas.<br>\n<br>Aquí podrás gestionar información de los alumnos, docentes y staff de la Universidad de Lima.<br>\n<br>Toda la información ingresada estará a su disposición a través del menú a la izquierda.<br>\n<br>Tan solo elige una de las opciones a la izquierda para iniciar con el proceso de gestión de personas.\n</html>");

        jLabel3.setForeground(new java.awt.Color(155, 197, 225));
        jLabel3.setText("Version 1.3 - beta @gestorversion1.3");

        javax.swing.GroupLayout About_PanelLayout = new javax.swing.GroupLayout(About_Panel);
        About_Panel.setLayout(About_PanelLayout);
        About_PanelLayout.setHorizontalGroup(
            About_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(About_PanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(About_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addGap(66, 66, 66))
        );
        About_PanelLayout.setVerticalGroup(
            About_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(About_PanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(66, 66, 66)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        CardLayout.add(About_Panel, "card2");

        Alumno_Panel.setBackground(new java.awt.Color(52, 60, 64));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Book", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Gestión de Alumnos");

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Book", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Seleccionar la opción que desee gestionar.");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paquete/recursos/Agregar.png"))); // NOI18N
        jLabel7.setText("  Agregar Alumno");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paquete/recursos/Eliminar.png"))); // NOI18N
        jLabel8.setText("  Eliminar Alumno");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Nombre:");

        nombre_alumno.setBackground(new java.awt.Color(52, 60, 64));
        nombre_alumno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombre_alumno.setForeground(new java.awt.Color(255, 255, 255));
        nombre_alumno.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        nombre_alumno.setCaretColor(new java.awt.Color(255, 255, 255));
        nombre_alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_alumnoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Distrito:");

        distrito_alumno.setBackground(new java.awt.Color(52, 60, 64));
        distrito_alumno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        distrito_alumno.setForeground(new java.awt.Color(255, 255, 255));
        distrito_alumno.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        distrito_alumno.setCaretColor(new java.awt.Color(255, 255, 255));
        distrito_alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distrito_alumnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Alumno_PanelLayout = new javax.swing.GroupLayout(Alumno_Panel);
        Alumno_Panel.setLayout(Alumno_PanelLayout);
        Alumno_PanelLayout.setHorizontalGroup(
            Alumno_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Alumno_PanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(Alumno_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Alumno_PanelLayout.createSequentialGroup()
                        .addGroup(Alumno_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Alumno_PanelLayout.createSequentialGroup()
                        .addGroup(Alumno_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Alumno_PanelLayout.createSequentialGroup()
                                .addGroup(Alumno_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Alumno_PanelLayout.createSequentialGroup()
                                .addGroup(Alumno_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Alumno_PanelLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(7, 7, 7))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Alumno_PanelLayout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(Alumno_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombre_alumno, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                    .addComponent(distrito_alumno))
                                .addGap(32, 32, 32)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );
        Alumno_PanelLayout.setVerticalGroup(
            Alumno_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Alumno_PanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGroup(Alumno_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Alumno_PanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Alumno_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(nombre_alumno))
                        .addGap(15, 15, 15)
                        .addGroup(Alumno_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(distrito_alumno))
                        .addGap(37, 37, 37)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(221, 221, 221))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Alumno_PanelLayout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(94, 94, 94))
        );

        CardLayout.add(Alumno_Panel, "card3");

        jSplitPane1.setRightComponent(CardLayout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1223, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Alum_Main_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Alum_Main_LabelMouseClicked
        // TODO add your handling code here:
        
        this.Alumno_Panel.setVisible(true);
        this.About_Panel.setVisible(false);
        

        

        

    }//GEN-LAST:event_Alum_Main_LabelMouseClicked

    private void Alum_Main_LabelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Alum_Main_LabelFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Alum_Main_LabelFocusGained

    private void About_MainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_About_MainMouseClicked
        // TODO add your handling code here:
        this.About_Panel.setVisible(true);
        this.Alumno_Panel.setVisible(false);
        
        
    }//GEN-LAST:event_About_MainMouseClicked

    private void nombre_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_alumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_alumnoActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        
        String nom = this.nombre_alumno.getText();
        String distrito = this.distrito_alumno.getText();
        int cur = Integer.parseInt(JOptionPane.showInputDialog("Cuantos cursos matriculados?"));
        
        Alumno alum = new Alumno(nom, distrito, cur);
        alum.GenerarCodigo();
        
        System.out.println(alum.getCodigo());
        
        alum.SolicitarNotas();
        
        galumnos.Agregar(alum);
        
        //PoblarTabla(modelo_alumno, galumnos);
        
    }//GEN-LAST:event_jLabel7MouseClicked

    private void distrito_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distrito_alumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_distrito_alumnoActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        
        galumnos.Eliminar(jTable1.getSelectedRow());
        //PoblarTabla(modelo_alumno, galumnos);
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_V2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_V2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_V2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_V2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_V2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel About_Main;
    private javax.swing.JPanel About_Panel;
    private javax.swing.JLabel Alum_Main_Label;
    private javax.swing.JPanel Alumno_Panel;
    private javax.swing.JPanel CardLayout;
    private javax.swing.JLabel Doc_Main_Label;
    private javax.swing.JPanel Side_Menu;
    private javax.swing.JLabel Staff_Main_Label;
    private javax.swing.JTextField distrito_alumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nombre_alumno;
    // End of variables declaration//GEN-END:variables

    
    /*
    private void PoblarTabla(DefaultTableModel mod){
        
        int cont = mod.getRowCount();
        
        for(int i=0;i<cont;i++){
            mod.removeRow(0);
        }
        
        String datos[] = new String[10];
        
        Alumno[] arreglo_alumno = gp.getArreglo();
        Docente[] arreglo_docente = gp.getArreglo();
        
        
        
        
        if(gp.getTipo() == 1){
            for(int i=0;i<gp.getContador();i++){

                datos[0] = arreglo_alumno[i].getNombre();
                datos[1] = arreglo_alumno[i].getCodigo();
                datos[2] = arreglo_alumno[i].getDistrito();

                datos[3] = String.valueOf(arreglo_alumno[i].getCur());
                datos[4] = String.valueOf(arreglo_alumno[i].getPromTotal());

                mod.addRow(datos);
            }
        }
    }
    */
}
