/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paquete.GUI;

import paquete.clases.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import paquete.gestion.*;

/**
 *
 * @author Nikolas
 */
public class Ventana_V2 extends javax.swing.JFrame {
    
    Tabla modelo_alumno;
    Tabla modelo_docente;
    Tabla modelo_staff;
    
    Gestion galumnos, gprofes, gstaff;
    Loading load = new Loading();
    
    /**
     * Creates new form Ventana_V2
     */
    public Ventana_V2() {
        
        modelo_alumno = new Tabla("Alumno");
        modelo_docente = new Tabla("Docente");
        modelo_staff = new Tabla("Staff");
        
        galumnos = new Gestion();
        gprofes = new Gestion();
        gstaff = new Gestion();
        
        load.LoadingScreen("Iniciando Aplicación", 40);
        
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        
        //Tablas

        this.Tabla_Datos_Alumno.setModel(modelo_alumno);
        this.Tabla_Datos_Docente.setModel(modelo_docente);
        this.Tabla_Datos_Staff.setModel(modelo_staff);
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        Side_Menu = new javax.swing.JPanel();
        Alum_Main_Label = new javax.swing.JLabel();
        Doc_Main_Label = new javax.swing.JLabel();
        Staff_Main_Label = new javax.swing.JLabel();
        About_Main = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CardLayout = new javax.swing.JPanel();
        About_Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Alumno_Panel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Agregar_Alumno = new javax.swing.JLabel();
        Eliminar_Alumno = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Datos_Alumno = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        nombre_alumno = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        distrito_alumno = new javax.swing.JTextField();
        View_Alumno = new javax.swing.JLabel();
        Docente_Panel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Agregar_Docente = new javax.swing.JLabel();
        Eliminar_Docente = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla_Datos_Docente = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        nombre_docente = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        distrito_docente = new javax.swing.JTextField();
        View_Docente = new javax.swing.JLabel();
        Staff_Panel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Agregar_Staff = new javax.swing.JLabel();
        Eliminar_Staff = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabla_Datos_Staff = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        nombre_staff = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        distrito_staff = new javax.swing.JTextField();
        View_Staff = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TRABAJO_FINAL");
        setResizable(false);

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setDividerSize(0);

        Side_Menu.setBackground(new java.awt.Color(242, 167, 27));
        Side_Menu.setMinimumSize(new java.awt.Dimension(200, 0));
        Side_Menu.setPreferredSize(new java.awt.Dimension(250, 677));

        Alum_Main_Label.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        Alum_Main_Label.setForeground(new java.awt.Color(255, 255, 255));
        Alum_Main_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paquete/recursos/Student.png"))); // NOI18N
        Alum_Main_Label.setText("  Alumnos");
        Alum_Main_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Alum_Main_Label.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Alum_Main_LabelFocusGained(evt);
            }
        });
        Alum_Main_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Alum_Main_LabelMouseClicked(evt);
            }
        });

        Doc_Main_Label.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        Doc_Main_Label.setForeground(new java.awt.Color(255, 255, 255));
        Doc_Main_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paquete/recursos/Teacher.png"))); // NOI18N
        Doc_Main_Label.setText("  Docentes");
        Doc_Main_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Doc_Main_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Doc_Main_LabelMouseClicked(evt);
            }
        });

        Staff_Main_Label.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        Staff_Main_Label.setForeground(new java.awt.Color(255, 255, 255));
        Staff_Main_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paquete/recursos/Staff.png"))); // NOI18N
        Staff_Main_Label.setText("  Staff");
        Staff_Main_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Staff_Main_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Staff_Main_LabelMouseClicked(evt);
            }
        });

        About_Main.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        About_Main.setForeground(new java.awt.Color(255, 255, 255));
        About_Main.setText("About");
        About_Main.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        About_Main.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                About_MainMouseClicked(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paquete/recursos/Logo.png"))); // NOI18N
        jLabel10.setAlignmentX(0.5F);
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Side_MenuLayout = new javax.swing.GroupLayout(Side_Menu);
        Side_Menu.setLayout(Side_MenuLayout);
        Side_MenuLayout.setHorizontalGroup(
            Side_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Side_MenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Side_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Side_MenuLayout.createSequentialGroup()
                        .addGroup(Side_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Staff_Main_Label)
                            .addComponent(Doc_Main_Label)
                            .addGroup(Side_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10)
                                .addComponent(Alum_Main_Label)))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Side_MenuLayout.createSequentialGroup()
                        .addComponent(About_Main)
                        .addContainerGap())))
        );
        Side_MenuLayout.setVerticalGroup(
            Side_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Side_MenuLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel10)
                .addGap(54, 54, 54)
                .addComponent(Alum_Main_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(Doc_Main_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(Staff_Main_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(317, 317, 317)
                .addComponent(About_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(Side_Menu);

        CardLayout.setLayout(new java.awt.CardLayout());

        About_Panel.setBackground(new java.awt.Color(52, 60, 64));
        About_Panel.setPreferredSize(new java.awt.Dimension(680, 600));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seleccionar las cuentas que desee gestionar.");

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Book", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Applicación Gestión de Personas");

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Book", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html>Bienvenidos al gestor de personas.<br>\n<br>Aquí podrás gestionar información de los alumnos, docentes y staff de la Universidad de Lima.<br>\n<br>Toda la información ingresada estará a su disposición a través del menú a la izquierda.<br>\n<br>Tan solo elige una de las opciones a la izquierda para iniciar con el proceso de gestión de personas.\n</html>");

        jLabel3.setForeground(new java.awt.Color(155, 197, 225));
        jLabel3.setText("Version 1.3 - alpha @gestorversion1.3");

        javax.swing.GroupLayout About_PanelLayout = new javax.swing.GroupLayout(About_Panel);
        About_Panel.setLayout(About_PanelLayout);
        About_PanelLayout.setHorizontalGroup(
            About_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(About_PanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(About_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addGap(66, 66, 66))
        );
        About_PanelLayout.setVerticalGroup(
            About_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(About_PanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(66, 66, 66)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        CardLayout.add(About_Panel, "card2");

        Alumno_Panel.setBackground(new java.awt.Color(52, 60, 64));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Book", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Gestión de Alumnos");

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Book", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Seleccionar la opción que desee gestionar.");

        Agregar_Alumno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Agregar_Alumno.setForeground(new java.awt.Color(255, 255, 255));
        Agregar_Alumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paquete/recursos/Agregar.png"))); // NOI18N
        Agregar_Alumno.setText("  Agregar Alumno");
        Agregar_Alumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Agregar_Alumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Agregar_AlumnoMouseClicked(evt);
            }
        });

        Eliminar_Alumno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Eliminar_Alumno.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar_Alumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paquete/recursos/Trash.png"))); // NOI18N
        Eliminar_Alumno.setText("  Eliminar Alumno");
        Eliminar_Alumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Eliminar_Alumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Eliminar_AlumnoMouseClicked(evt);
            }
        });

        Tabla_Datos_Alumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tabla_Datos_Alumno);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Nombre:");

        nombre_alumno.setBackground(new java.awt.Color(52, 60, 64));
        nombre_alumno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombre_alumno.setForeground(new java.awt.Color(255, 255, 255));
        nombre_alumno.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        nombre_alumno.setCaretColor(new java.awt.Color(255, 255, 255));
        nombre_alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_alumnoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Distrito:");

        distrito_alumno.setBackground(new java.awt.Color(52, 60, 64));
        distrito_alumno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        distrito_alumno.setForeground(new java.awt.Color(255, 255, 255));
        distrito_alumno.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        distrito_alumno.setCaretColor(new java.awt.Color(255, 255, 255));
        distrito_alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distrito_alumnoActionPerformed(evt);
            }
        });

        View_Alumno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        View_Alumno.setForeground(new java.awt.Color(255, 255, 255));
        View_Alumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paquete/recursos/Ver.png"))); // NOI18N
        View_Alumno.setText("Ver Detalle");
        View_Alumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        View_Alumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                View_AlumnoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Alumno_PanelLayout = new javax.swing.GroupLayout(Alumno_Panel);
        Alumno_Panel.setLayout(Alumno_PanelLayout);
        Alumno_PanelLayout.setHorizontalGroup(
            Alumno_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Alumno_PanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(Alumno_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Alumno_PanelLayout.createSequentialGroup()
                        .addGroup(Alumno_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Alumno_PanelLayout.createSequentialGroup()
                        .addGroup(Alumno_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Alumno_PanelLayout.createSequentialGroup()
                                .addGroup(Alumno_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Eliminar_Alumno)
                                    .addComponent(Agregar_Alumno))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE))
                            .addGroup(Alumno_PanelLayout.createSequentialGroup()
                                .addGroup(Alumno_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Alumno_PanelLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(7, 7, 7))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Alumno_PanelLayout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(Alumno_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombre_alumno, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                    .addComponent(distrito_alumno))
                                .addGap(32, 32, 32)))
                        .addGroup(Alumno_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(View_Alumno)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))))
        );
        Alumno_PanelLayout.setVerticalGroup(
            Alumno_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Alumno_PanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(Alumno_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nombre_alumno))
                .addGap(15, 15, 15)
                .addGroup(Alumno_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(distrito_alumno))
                .addGap(37, 37, 37)
                .addComponent(Agregar_Alumno)
                .addGap(18, 18, 18)
                .addComponent(Eliminar_Alumno)
                .addGap(315, 315, 315))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Alumno_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(View_Alumno)
                .addGap(94, 94, 94))
        );

        CardLayout.add(Alumno_Panel, "card3");

        Docente_Panel.setBackground(new java.awt.Color(52, 60, 64));

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Book", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Gestión de Docentes");

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Book", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Seleccionar la opción que desee gestionar.");

        Agregar_Docente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Agregar_Docente.setForeground(new java.awt.Color(255, 255, 255));
        Agregar_Docente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paquete/recursos/Agregar.png"))); // NOI18N
        Agregar_Docente.setText("  Agregar Docente");
        Agregar_Docente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Agregar_Docente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Agregar_DocenteMouseClicked(evt);
            }
        });

        Eliminar_Docente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Eliminar_Docente.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar_Docente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paquete/recursos/Trash.png"))); // NOI18N
        Eliminar_Docente.setText("  Eliminar Docente");
        Eliminar_Docente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Eliminar_Docente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Eliminar_DocenteMouseClicked(evt);
            }
        });

        Tabla_Datos_Docente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(Tabla_Datos_Docente);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Nombre:");

        nombre_docente.setBackground(new java.awt.Color(52, 60, 64));
        nombre_docente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombre_docente.setForeground(new java.awt.Color(255, 255, 255));
        nombre_docente.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        nombre_docente.setCaretColor(new java.awt.Color(255, 255, 255));
        nombre_docente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_docenteActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Distrito:");

        distrito_docente.setBackground(new java.awt.Color(52, 60, 64));
        distrito_docente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        distrito_docente.setForeground(new java.awt.Color(255, 255, 255));
        distrito_docente.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        distrito_docente.setCaretColor(new java.awt.Color(255, 255, 255));
        distrito_docente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distrito_docenteActionPerformed(evt);
            }
        });

        View_Docente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        View_Docente.setForeground(new java.awt.Color(255, 255, 255));
        View_Docente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paquete/recursos/Ver.png"))); // NOI18N
        View_Docente.setText("Ver Detalle");
        View_Docente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        View_Docente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                View_DocenteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Docente_PanelLayout = new javax.swing.GroupLayout(Docente_Panel);
        Docente_Panel.setLayout(Docente_PanelLayout);
        Docente_PanelLayout.setHorizontalGroup(
            Docente_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Docente_PanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(Docente_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Docente_PanelLayout.createSequentialGroup()
                        .addGroup(Docente_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Docente_PanelLayout.createSequentialGroup()
                        .addGroup(Docente_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Docente_PanelLayout.createSequentialGroup()
                                .addGroup(Docente_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Eliminar_Docente)
                                    .addComponent(Agregar_Docente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE))
                            .addGroup(Docente_PanelLayout.createSequentialGroup()
                                .addGroup(Docente_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Docente_PanelLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(7, 7, 7))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Docente_PanelLayout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(Docente_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombre_docente, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                                    .addComponent(distrito_docente))
                                .addGap(32, 32, 32)))
                        .addGroup(Docente_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(View_Docente)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))))
        );
        Docente_PanelLayout.setVerticalGroup(
            Docente_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Docente_PanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(Docente_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(nombre_docente))
                .addGap(15, 15, 15)
                .addGroup(Docente_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(distrito_docente))
                .addGap(37, 37, 37)
                .addComponent(Agregar_Docente)
                .addGap(18, 18, 18)
                .addComponent(Eliminar_Docente)
                .addGap(315, 315, 315))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Docente_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(View_Docente)
                .addGap(94, 94, 94))
        );

        CardLayout.add(Docente_Panel, "card3");

        Staff_Panel.setBackground(new java.awt.Color(52, 60, 64));

        jLabel14.setFont(new java.awt.Font("Franklin Gothic Book", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Gestión de Staff");

        jLabel15.setFont(new java.awt.Font("Franklin Gothic Book", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Seleccionar la opción que desee gestionar.");

        Agregar_Staff.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Agregar_Staff.setForeground(new java.awt.Color(255, 255, 255));
        Agregar_Staff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paquete/recursos/Agregar.png"))); // NOI18N
        Agregar_Staff.setText("  Agregar Staff");
        Agregar_Staff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Agregar_Staff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Agregar_StaffMouseClicked(evt);
            }
        });

        Eliminar_Staff.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Eliminar_Staff.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar_Staff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paquete/recursos/Trash.png"))); // NOI18N
        Eliminar_Staff.setText("  Eliminar Staff");
        Eliminar_Staff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Eliminar_Staff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Eliminar_StaffMouseClicked(evt);
            }
        });

        Tabla_Datos_Staff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(Tabla_Datos_Staff);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Nombre:");

        nombre_staff.setBackground(new java.awt.Color(52, 60, 64));
        nombre_staff.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombre_staff.setForeground(new java.awt.Color(255, 255, 255));
        nombre_staff.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        nombre_staff.setCaretColor(new java.awt.Color(255, 255, 255));
        nombre_staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_staffActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Distrito:");

        distrito_staff.setBackground(new java.awt.Color(52, 60, 64));
        distrito_staff.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        distrito_staff.setForeground(new java.awt.Color(255, 255, 255));
        distrito_staff.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        distrito_staff.setCaretColor(new java.awt.Color(255, 255, 255));
        distrito_staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distrito_staffActionPerformed(evt);
            }
        });

        View_Staff.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        View_Staff.setForeground(new java.awt.Color(255, 255, 255));
        View_Staff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paquete/recursos/Ver.png"))); // NOI18N
        View_Staff.setText("Ver Detalle");
        View_Staff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        View_Staff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                View_StaffMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Staff_PanelLayout = new javax.swing.GroupLayout(Staff_Panel);
        Staff_Panel.setLayout(Staff_PanelLayout);
        Staff_PanelLayout.setHorizontalGroup(
            Staff_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Staff_PanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(Staff_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Staff_PanelLayout.createSequentialGroup()
                        .addGroup(Staff_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Staff_PanelLayout.createSequentialGroup()
                        .addGroup(Staff_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Staff_PanelLayout.createSequentialGroup()
                                .addGroup(Staff_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Eliminar_Staff)
                                    .addComponent(Agregar_Staff))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE))
                            .addGroup(Staff_PanelLayout.createSequentialGroup()
                                .addGroup(Staff_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Staff_PanelLayout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(7, 7, 7))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Staff_PanelLayout.createSequentialGroup()
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(Staff_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombre_staff, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                                    .addComponent(distrito_staff))
                                .addGap(32, 32, 32)))
                        .addGroup(Staff_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(View_Staff)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))))
        );
        Staff_PanelLayout.setVerticalGroup(
            Staff_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Staff_PanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(Staff_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(nombre_staff))
                .addGap(15, 15, 15)
                .addGroup(Staff_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(distrito_staff))
                .addGap(37, 37, 37)
                .addComponent(Agregar_Staff)
                .addGap(18, 18, 18)
                .addComponent(Eliminar_Staff)
                .addGap(315, 315, 315))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Staff_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(View_Staff)
                .addGap(94, 94, 94))
        );

        CardLayout.add(Staff_Panel, "card3");

        jSplitPane1.setRightComponent(CardLayout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1223, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Alum_Main_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Alum_Main_LabelMouseClicked
        // TODO add your handling code here:
        
        this.Alumno_Panel.setVisible(true);
        this.About_Panel.setVisible(false);
        this.Docente_Panel.setVisible(false);
        

        

        

    }//GEN-LAST:event_Alum_Main_LabelMouseClicked

    private void Alum_Main_LabelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Alum_Main_LabelFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Alum_Main_LabelFocusGained

    private void About_MainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_About_MainMouseClicked
        // TODO add your handling code here:
        this.About_Panel.setVisible(true);
        
        this.Alumno_Panel.setVisible(false);
        this.Staff_Panel.setVisible(false);
        this.Docente_Panel.setVisible(false);
        
        
    }//GEN-LAST:event_About_MainMouseClicked

    private void nombre_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_alumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_alumnoActionPerformed

    private void Agregar_AlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Agregar_AlumnoMouseClicked
        // TODO add your handling code here:
        
        String nom = this.nombre_alumno.getText();
        String distrito = this.distrito_alumno.getText();
        
        if("".equals(nom) || "".equals(distrito)){
            
            JOptionPane.showMessageDialog(null, "Por favor completar los campos vacíos.");
            
        } else {
        
            try{
                int cur = Integer.parseInt(JOptionPane.showInputDialog("Cuantos cursos matriculados?"));

                Alumno alum = new Alumno(nom, distrito, cur);
                alum.GenerarCodigo();

                System.out.println(alum.getCodigo());

                alum.SolicitarNotas();

                galumnos.Agregar(alum);

                PoblarTabla(modelo_alumno, galumnos, "Alumno");
            } catch (Exception e) {}
            
        }
    }//GEN-LAST:event_Agregar_AlumnoMouseClicked

    private void distrito_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distrito_alumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_distrito_alumnoActionPerformed

    private void Eliminar_AlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Eliminar_AlumnoMouseClicked
        // TODO add your handling code here:
        
        galumnos.Eliminar(Tabla_Datos_Alumno.getSelectedRow());
        
        PoblarTabla(modelo_alumno, galumnos, "Alumno");
    }//GEN-LAST:event_Eliminar_AlumnoMouseClicked

    
    
    private void View_AlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_View_AlumnoMouseClicked
        // TODO add your handling code here:
        try{
            int selec = this.Tabla_Datos_Alumno.getSelectedRow();
            
            if(this.Tabla_Datos_Alumno.getRowCount()  > 0 && selec >= 0){
                
                Datos datos_alum = new Datos(galumnos, "Alumno", selec);
                
            } else {
                JOptionPane.showMessageDialog(null, "Debe haber al menos un alumno seleccionado.");
            }
            
        } catch(Exception e){}
    }//GEN-LAST:event_View_AlumnoMouseClicked

    
    
    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        
        this.About_Panel.setVisible(true);
        
        this.Alumno_Panel.setVisible(false);
        this.Staff_Panel.setVisible(false);
        this.Docente_Panel.setVisible(false);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void Agregar_DocenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Agregar_DocenteMouseClicked
        // TODO add your handling code here:
        String nom = this.nombre_docente.getText();
        String distrito = this.distrito_docente.getText();
        
        if("".equals(nom) || "".equals(distrito)){
            
            JOptionPane.showMessageDialog(null, "Por favor completar los campos vacíos.");
            
        } else {
        
            try{
                int cur = Integer.parseInt(JOptionPane.showInputDialog("Cuantos cursos enseñará?"));

                Docente doc = new Docente(nom, distrito, cur);
                doc.GenerarCodigo();

                System.out.println(doc.getCodigo());

                doc.SolicitarHoras();
                
                doc.CalcularSueldo();
                
                gprofes.Agregar(doc);

                PoblarTabla(modelo_docente, gprofes, "Docente");
            } catch (Exception e) {}
            
        }
    }//GEN-LAST:event_Agregar_DocenteMouseClicked

    private void Eliminar_DocenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Eliminar_DocenteMouseClicked
        // TODO add your handling code here:
        gprofes.Eliminar(Tabla_Datos_Docente.getSelectedRow());
        
        PoblarTabla(modelo_docente, gprofes, "Docentes");
        
        
    }//GEN-LAST:event_Eliminar_DocenteMouseClicked

    private void nombre_docenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_docenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_docenteActionPerformed

    private void distrito_docenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distrito_docenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_distrito_docenteActionPerformed

    private void View_DocenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_View_DocenteMouseClicked
        // TODO add your handling code here:
        try{
            int selec = this.Tabla_Datos_Docente.getSelectedRow();
            
            if(this.Tabla_Datos_Docente.getRowCount()  > 0 && selec >= 0){
                
                Datos datos_docente = new Datos(gprofes, "Docente", selec);
                
            } else {
                JOptionPane.showMessageDialog(null, "Debe haber al menos un docente seleccionado.");
            }
            
        } catch(Exception e){
            System.out.println("Error en cargar datos extra_Docente");
        }
        
    }//GEN-LAST:event_View_DocenteMouseClicked

    private void Doc_Main_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Doc_Main_LabelMouseClicked
        // TODO add your handling code here:
        
        this.Alumno_Panel.setVisible(false);
        this.About_Panel.setVisible(false);
        this.Staff_Panel.setVisible(false);
        
        this.Docente_Panel.setVisible(true);
        
        
        
    }//GEN-LAST:event_Doc_Main_LabelMouseClicked

    private void Agregar_StaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Agregar_StaffMouseClicked
        // TODO add your handling code here:
        String nom = this.nombre_staff.getText();
        String distrito = this.distrito_staff.getText();
        
        if("".equals(nom) || "".equals(distrito)){
            
            JOptionPane.showMessageDialog(null, "Por favor completar los campos vacíos.");
            
        } else {
            
            try{
                
                String psto = JOptionPane.showInputDialog("Ingresar puesto");
                
                int cur = Integer.parseInt(JOptionPane.showInputDialog("Cuántas responsabilidades tiene?"));

                Staff staff = new Staff(nom, distrito, psto, cur);
                staff.GenerarCodigo();

                System.out.println(staff.getCodigo());

                staff.SolicitarHoras();
                
                staff.CalcularSueldo();
                
                gstaff.Agregar(staff);

                PoblarTabla(modelo_staff, gstaff, "Staff");
            } catch (Exception e) {}
            
        }
    }//GEN-LAST:event_Agregar_StaffMouseClicked

    private void Eliminar_StaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Eliminar_StaffMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Eliminar_StaffMouseClicked

    private void nombre_staffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_staffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_staffActionPerformed

    private void distrito_staffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distrito_staffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_distrito_staffActionPerformed

    private void View_StaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_View_StaffMouseClicked
        // TODO add your handling code here:
        try{
            int selec = this.Tabla_Datos_Staff.getSelectedRow();
            
            if(this.Tabla_Datos_Staff.getRowCount()  > 0 && selec >= 0){
                
                Datos datos_docente = new Datos(gstaff, "Staff", selec);
                
            } else {
                JOptionPane.showMessageDialog(null, "Debe haber al menos un staff seleccionado.");
            }
            
        } catch(Exception e){
            System.out.println("Error en cargar datos extra_Staff");
        }
    }//GEN-LAST:event_View_StaffMouseClicked

    private void Staff_Main_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Staff_Main_LabelMouseClicked
        // TODO add your handling code here:
        this.About_Panel.setVisible(false);
        this.Alumno_Panel.setVisible(false);
        
        this.Staff_Panel.setVisible(true);
        
        this.Docente_Panel.setVisible(false);
        
    }//GEN-LAST:event_Staff_Main_LabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_V2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_V2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_V2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_V2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_V2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel About_Main;
    private javax.swing.JPanel About_Panel;
    private javax.swing.JLabel Agregar_Alumno;
    private javax.swing.JLabel Agregar_Docente;
    private javax.swing.JLabel Agregar_Staff;
    private javax.swing.JLabel Alum_Main_Label;
    private javax.swing.JPanel Alumno_Panel;
    private javax.swing.JPanel CardLayout;
    private javax.swing.JLabel Doc_Main_Label;
    private javax.swing.JPanel Docente_Panel;
    private javax.swing.JLabel Eliminar_Alumno;
    private javax.swing.JLabel Eliminar_Docente;
    private javax.swing.JLabel Eliminar_Staff;
    private javax.swing.JPanel Side_Menu;
    private javax.swing.JLabel Staff_Main_Label;
    private javax.swing.JPanel Staff_Panel;
    private javax.swing.JTable Tabla_Datos_Alumno;
    private javax.swing.JTable Tabla_Datos_Docente;
    private javax.swing.JTable Tabla_Datos_Staff;
    private javax.swing.JLabel View_Alumno;
    private javax.swing.JLabel View_Docente;
    private javax.swing.JLabel View_Staff;
    private javax.swing.JTextField distrito_alumno;
    private javax.swing.JTextField distrito_docente;
    private javax.swing.JTextField distrito_staff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField nombre_alumno;
    private javax.swing.JTextField nombre_docente;
    private javax.swing.JTextField nombre_staff;
    // End of variables declaration//GEN-END:variables

    
    
    private void PoblarTabla(DefaultTableModel mod, Gestion gp, String abc){
        
        int cont = mod.getRowCount();
        
        for(int i=0;i<cont;i++){
            mod.removeRow(0);
        }
        
        String datos[] = new String[10];
        
        Persona[] arreglo = gp.getArreglo();
        
        try{
            for(int i=0;i<gp.getContador();i++){
                datos[0] = arreglo[i].getNombre();
                datos[1] = arreglo[i].getCodigo();
                datos[2] = arreglo[i].getDistrito();

                if(abc.equalsIgnoreCase("Alumno")){

                    datos[3] = String.valueOf(((Alumno)arreglo[i]).getCur());
                    datos[4] = String.valueOf(((Alumno)arreglo[i]).getPromTotal());

                } else if(abc.equalsIgnoreCase("Docente")){
                    
                    datos[3] = String.valueOf(((Docente)arreglo[i]).getCur());
                    datos[4] = String.valueOf(((Docente)arreglo[i]).getTotalHrs());
                    datos[5] = String.valueOf(((Docente)arreglo[i]).getSueldo());
                    
                } else if(abc.equalsIgnoreCase("Staff")){
                    
                    datos[3] = ((Staff)arreglo[i]).getPuesto();
                    datos[4] = String.valueOf(((Staff)arreglo[i]).getResp());
                    datos[5] = String.valueOf(((Staff)arreglo[i]).getTotalHrs());
                    datos[6] = String.valueOf(((Staff)arreglo[i]).getSueldo());
                    
                }

                mod.addRow(datos);

            }
            
        } catch(Exception e){
            System.out.println("Error en poblar tabla");
        }
    }
    
}
