/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paquete.GUI;

import java.awt.Toolkit;

/**
 *
 * @author Nikolas
 */
public class Ventana_V2 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_V2
     */
    public Ventana_V2() {
        initComponents();
        SetIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        Side_Menu = new javax.swing.JPanel();
        Alum_Main_Label = new javax.swing.JLabel();
        Doc_Main_Label = new javax.swing.JLabel();
        Staff_Main_Label = new javax.swing.JLabel();
        CardLayout = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TRABAJO_FINAL");

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setDividerSize(0);

        Side_Menu.setBackground(new java.awt.Color(242, 167, 27));
        Side_Menu.setMinimumSize(new java.awt.Dimension(200, 0));
        Side_Menu.setPreferredSize(new java.awt.Dimension(250, 677));

        Alum_Main_Label.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        Alum_Main_Label.setForeground(new java.awt.Color(255, 255, 255));
        Alum_Main_Label.setText("Alumnos");
        Alum_Main_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Alum_Main_LabelMouseClicked(evt);
            }
        });

        Doc_Main_Label.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        Doc_Main_Label.setForeground(new java.awt.Color(255, 255, 255));
        Doc_Main_Label.setText("Docentes");

        Staff_Main_Label.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        Staff_Main_Label.setForeground(new java.awt.Color(255, 255, 255));
        Staff_Main_Label.setText("Staff");

        javax.swing.GroupLayout Side_MenuLayout = new javax.swing.GroupLayout(Side_Menu);
        Side_Menu.setLayout(Side_MenuLayout);
        Side_MenuLayout.setHorizontalGroup(
            Side_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Side_MenuLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(Side_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Staff_Main_Label)
                    .addComponent(Alum_Main_Label)
                    .addComponent(Doc_Main_Label))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        Side_MenuLayout.setVerticalGroup(
            Side_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Side_MenuLayout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(Alum_Main_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(49, 49, 49)
                .addComponent(Doc_Main_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(49, 49, 49)
                .addComponent(Staff_Main_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(331, 331, 331))
        );

        jSplitPane1.setLeftComponent(Side_Menu);

        CardLayout.setLayout(new java.awt.CardLayout());

        Menu.setBackground(new java.awt.Color(52, 60, 64));
        Menu.setPreferredSize(new java.awt.Dimension(680, 600));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seleccionar las cuentas que desee gestionar.");

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Book", 1, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Applicación Gestión de Personas");

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Book", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html>Bienvenidos al gestor de personas.<br>\n<br>Aquí podrás gestionar información de los alumnos, docentes y staff de la Universidad de Lima.<br>\n<br>Toda la información ingresada estará a su disposición a través del menú a la izquierda.<br>\n<br>Tan solo elige una de las opciones a la izquierda para iniciar con el proceso de gestión de personas.\n</html>");

        jLabel3.setForeground(new java.awt.Color(155, 197, 225));
        jLabel3.setText("Version 1.3 - beta @gestorversion1.3");

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addGap(347, 347, 347))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(66, 66, 66)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 297, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        CardLayout.add(Menu, "card2");

        jSplitPane1.setRightComponent(CardLayout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1454, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Alum_Main_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Alum_Main_LabelMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Alum_Main_LabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_V2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_V2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_V2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_V2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_V2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alum_Main_Label;
    private javax.swing.JPanel CardLayout;
    private javax.swing.JLabel Doc_Main_Label;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel Side_Menu;
    private javax.swing.JLabel Staff_Main_Label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables

    private void SetIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("persona.png")));
    }
    
    public static String convertToMultiline(String orig){
        return "<html>" + orig.replaceAll("\n", "<br>");
    }
    
}
